package studio.rashka.Test;

public class Question4 {

    public StringBuilder[] V4 = new StringBuilder[]{
            new StringBuilder("865 год"),
            new StringBuilder("855-861 гг."),
            new StringBuilder("1129 году"),
            new StringBuilder("5"),
            new StringBuilder("Эдуард"),
            new StringBuilder("Серебро"),
            new StringBuilder("Священниками"),
            new StringBuilder("рабочий скот"),
            new StringBuilder("пушка"),
            new StringBuilder("901 году"),
            new StringBuilder("800-м году"),
            new StringBuilder("1137 году"),
            new StringBuilder("Путивле"),
            new StringBuilder("Такого не было"),
            new StringBuilder("Князь Святослав"),
            new StringBuilder("1150"),
            new StringBuilder("Олегом"),
            new StringBuilder("богатые купцы"),
            new StringBuilder("Изяслав"),
            new StringBuilder("978-1054"),
            new StringBuilder("1015-1023"),
            new StringBuilder("1037-1075"),
            new StringBuilder("1054-1082"),
            new StringBuilder("1030-1093"),
            new StringBuilder("1073-1093"),
            new StringBuilder("861-911"),
            new StringBuilder("880-920"),
            new StringBuilder("879 году"),
            new StringBuilder("ремесло"),
            new StringBuilder("1112 году"),
            new StringBuilder("Служащими феодалам"),
            new StringBuilder("Князя"),
            new StringBuilder("Никак"),
            new StringBuilder("Баты"),
            new StringBuilder("1113 году"),
            new StringBuilder("съезд купцов"),
            new StringBuilder("рабство"),
            new StringBuilder("Класс купцов"),
            new StringBuilder("1193 году"),
            new StringBuilder("1165 и 1167 гг."),
            new StringBuilder("1212 году"),
            new StringBuilder("Смерд"),
            new StringBuilder("1341 год"),
            new StringBuilder("XIV"),
            new StringBuilder("Сбор дани"),
            new StringBuilder("972 год"),
            new StringBuilder("997 год"),
            new StringBuilder("1015-1035 гг."),
            new StringBuilder("873 год"),
            new StringBuilder("Крестьянская хижина"),
            new StringBuilder("Крепостные"),
            new StringBuilder("880 год"),
            new StringBuilder("налог с народа"),
            new StringBuilder("901 году"),
            new StringBuilder("912 году"),
            new StringBuilder("Тризна"),
            new StringBuilder("947 году"),
            new StringBuilder("Византия"),
            new StringBuilder("915-973"),
            new StringBuilder("Святославу"),
            new StringBuilder("Убила болезнь"),
            new StringBuilder("973 год"),
            new StringBuilder("Брак"),
            new StringBuilder("1061 год"),
            new StringBuilder("Изяслав"),
            new StringBuilder("Белук"),
            new StringBuilder("1132 год"),
            new StringBuilder("Острог"),
            new StringBuilder("Хорваты"),
            new StringBuilder("Бужане"),
            new StringBuilder("Верховья Буга"),
            new StringBuilder("Верховья Прута"),
            new StringBuilder("Северный Буг"),
            new StringBuilder("Река Стырь"),
            new StringBuilder("Река Буг"),
            new StringBuilder("Верховья Прута"),
            new StringBuilder("Правобережье Днестра"),
            new StringBuilder("992 год"),
            new StringBuilder("Средний Днестр"),
            new StringBuilder("Правобережье Буга"),
            new StringBuilder("1313 год"),
            new StringBuilder("В честь горы"),
            new StringBuilder("IV-VII"),
            new StringBuilder("966-968 гг."),
            new StringBuilder("Сахо"),
            new StringBuilder("880-883 гг."),
            new StringBuilder("Пушнина"),
            new StringBuilder("977 год"),
            new StringBuilder("Гермонасса"),
            new StringBuilder("Всеволод"),
            new StringBuilder("946 год"),
            new StringBuilder("Мир"),
            new StringBuilder("973 год"),
            new StringBuilder("С Оттоном I"),
            new StringBuilder("Печенеги"),
            new StringBuilder("Старик"),
            new StringBuilder("Олега"),
            new StringBuilder("Всех трех сторон"),
            new StringBuilder("Убит Лют Олегом"),
            new StringBuilder("992 год"),
            new StringBuilder("Дулебы"),
            new StringBuilder("989 году"),
            new StringBuilder("Владимир I"),
            new StringBuilder("Монголов"),
            new StringBuilder("992-997"),
            new StringBuilder("Москва"),
            new StringBuilder("1008 год"),
            new StringBuilder("1016 году"),
            new StringBuilder("1016 год"),
            new StringBuilder("1010 год"),
            new StringBuilder("1011 год"),
            new StringBuilder("1025 год"),
            new StringBuilder("склады пушнины"),
            new StringBuilder("Велеты"),
            new StringBuilder("Скотъ"),
            new StringBuilder("863 г."),
            new StringBuilder("чудовище"),
            new StringBuilder("изба"),
            new StringBuilder("862 г."),
            new StringBuilder("874 г."),
            new StringBuilder("870 г."),
            new StringBuilder("868 г."),
            new StringBuilder("Белозере"),
            new StringBuilder("875 г."),
            new StringBuilder("877 г."),
            new StringBuilder("872 г."),
            new StringBuilder("Дир"),
            new StringBuilder("Учителем"),
            new StringBuilder("880 г."),
            new StringBuilder("874 г."),
            new StringBuilder("870 г."),
            new StringBuilder("884 г."),
            new StringBuilder("881 г."),
            new StringBuilder("Синеус"),
            new StringBuilder("Византия"),
            new StringBuilder("Вячеслав"),
            new StringBuilder("885 г."),
            new StringBuilder("Ингвар Хререксон"),
            new StringBuilder("Купец"),
            new StringBuilder("Гостомысл"),
            new StringBuilder("Гостомысл"),
            new StringBuilder("864 г."),
            new StringBuilder("876 г."),
            new StringBuilder("Киев"),
            new StringBuilder("Византия"),
            new StringBuilder("879 г."),
            new StringBuilder("897 г."),
            new StringBuilder("919 г."),
            new StringBuilder("911 г."),
            new StringBuilder("Византию"),
            new StringBuilder("Аскольду"),
            new StringBuilder("Варягов"),
            new StringBuilder("Варягов"),
            new StringBuilder("Радимичей"),
            new StringBuilder("Ладья"),
            new StringBuilder("Гребка"),
            new StringBuilder("911 г."),
            new StringBuilder("по 12 гривен"),
            new StringBuilder("отравили"),
            new StringBuilder("900 г."),
            new StringBuilder("915-940 гг."),
            new StringBuilder("Рюрик"),
            new StringBuilder("Елизавета"),
            new StringBuilder("Иван"),
            new StringBuilder("Севастополь"),
            new StringBuilder("912 г."),
            new StringBuilder("931 г."),
            new StringBuilder("Отпустил"),
            new StringBuilder("Монголам"),
            new StringBuilder("915 г."),
            new StringBuilder("916 г."),
            new StringBuilder("Москвы"),
            new StringBuilder("948 г."),
            new StringBuilder("Царьград"),
            new StringBuilder("947-950 гг."),
            new StringBuilder("952 г."),
            new StringBuilder("в 24 года"),
            new StringBuilder("Древлян"),
            new StringBuilder("Выслал богатые дары"),
            new StringBuilder("961 г."),
            new StringBuilder("4"),
            new StringBuilder("948 г."),
            new StringBuilder("943 г."),
            new StringBuilder("958-968 гг."),
            new StringBuilder("928-958 гг."),
            new StringBuilder("6 раз"),
            new StringBuilder("947 г."),
            new StringBuilder("Всеволод"),
            new StringBuilder("955 г."),
            new StringBuilder("959 г."),
            new StringBuilder("Константинополь"),
            new StringBuilder("Наталья"),
            new StringBuilder("967 г."),
            new StringBuilder("Ветранион"),
            new StringBuilder("946 г."),
            new StringBuilder("Новгород"),
            new StringBuilder("950-970 гг."),
            new StringBuilder("947-957 гг."),
            new StringBuilder("945-969 гг."),
            new StringBuilder("Ярослав"),
            new StringBuilder("Изяслав"),
            new StringBuilder("947 год"),
            new StringBuilder("Ольга"),
            new StringBuilder("Киянка"),
            new StringBuilder("Обработка древесины"),
            new StringBuilder("Пахотное орудие"),
            new StringBuilder("Лодка"),
            new StringBuilder("V век"),
            new StringBuilder("Иудизм"),
            new StringBuilder("966 год"),
            new StringBuilder("Оттон I Великий"),
            new StringBuilder("974 год"),
            new StringBuilder("Игорь"),
            new StringBuilder("970 год"),
            new StringBuilder("964 год"),
            new StringBuilder("977 год"),
            new StringBuilder("973 год"),
            new StringBuilder("972/973 год"),
            new StringBuilder("968/969 год"),
            new StringBuilder("977 год"),
            new StringBuilder("974-975 гг."),
            new StringBuilder("972/973 год"),
            new StringBuilder("969 год"),
            new StringBuilder("Сфенкел"),
            new StringBuilder("977 год"),
            new StringBuilder("Лошадей"),
            new StringBuilder("971 год"),
            new StringBuilder("982 год"),
            new StringBuilder("980 год"),
            new StringBuilder("Редкие монеты"),
            new StringBuilder("968-969 гг."),
            new StringBuilder("250 кг"),
            new StringBuilder("975 год"),
            new StringBuilder("981 год"),
            new StringBuilder("Хазары"),
            new StringBuilder("985 год"),
            new StringBuilder("София"),
            new StringBuilder("Борису II"),
            new StringBuilder("3"),
            new StringBuilder("Святослав"),
            new StringBuilder("999 год"),
            new StringBuilder("974 год"),
            new StringBuilder("Владимир"),
            new StringBuilder("1029 год"),
            new StringBuilder("Борис II"),
            new StringBuilder("Иоанн Скилица"),
            new StringBuilder("955-978 гг."),
            new StringBuilder("Владимир"),
            new StringBuilder("976-984 гг."),
            new StringBuilder("Брак с княгиней"),
            new StringBuilder("977-978 гг."),
            new StringBuilder("Раздел власти"),
            new StringBuilder("981 г."),
            new StringBuilder("981 г."),
            new StringBuilder("Древлянские"),
            new StringBuilder("Суздальские"),
            new StringBuilder("Олег и Владимир"),
            new StringBuilder("977 г."),
            new StringBuilder("Кведлинбург"),
            new StringBuilder("Ярослав"),
            new StringBuilder("Юдит"),
            new StringBuilder("Ярослав"),
            new StringBuilder("Куно"),
            new StringBuilder("служанка"),
            new StringBuilder("Изяслав"),
            new StringBuilder("983 г."),
            new StringBuilder("Овруч"),
            new StringBuilder("Сбежал с воеводой"),
            new StringBuilder("Помог Ярополку"),
            new StringBuilder("984 г."),
            new StringBuilder("Варяги"),
            new StringBuilder("Князь Олег"),
            new StringBuilder("Полоцк"),
            new StringBuilder("Ремесленник"),
            new StringBuilder("Отрок"),
            new StringBuilder("Осквернил"),
            new StringBuilder("971-1021 гг."),
            new StringBuilder("972-992 гг."),
            new StringBuilder("978-1015 гг."),
            new StringBuilder("Деление власти"),
            new StringBuilder("Чума"),
            new StringBuilder("1002 г."),
            new StringBuilder("Василий"),
            new StringBuilder("Любеч"),
            new StringBuilder("Хамида"),
            new StringBuilder("Варяжко"),
            new StringBuilder("Олаф I Трюггвасон"),
            new StringBuilder("Хамида"),
            new StringBuilder("Наложил дань"),
            new StringBuilder("Хамида"),
            new StringBuilder("Рогнеде"),
            new StringBuilder("собрание крестьян"),
            new StringBuilder("гонтина"),
            new StringBuilder("алтарь"),
            new StringBuilder("Киев"),
            new StringBuilder("Мокошь"),
            new StringBuilder("Перун"),
            new StringBuilder("Хорс"),
            new StringBuilder("Стрибог"),
            new StringBuilder("Мокошь"),
            new StringBuilder("Велес"),
            new StringBuilder("Мокошь"),
            new StringBuilder("800"),
            new StringBuilder("отрубание бороды"),
            new StringBuilder("7"),
            new StringBuilder("нищий"),
            new StringBuilder("Схима"),
            new StringBuilder("Перун"),
            new StringBuilder("Мокошь"),
            new StringBuilder("Мокошь"),
            new StringBuilder("Белец"),
            new StringBuilder("Белец"),
            new StringBuilder("Пономарь"),
            new StringBuilder("Перун"),
            new StringBuilder("Причетник"),
            new StringBuilder("Схима"),
            new StringBuilder("старая изба"),
            new StringBuilder("990/991 г."),
            new StringBuilder("Бояре"),
            new StringBuilder("Святослав"),
            new StringBuilder("999 г."),
            new StringBuilder("996 г."),
            new StringBuilder("Варда Фока"),
            new StringBuilder("1010 г."),
            new StringBuilder("Севастополь"),
            new StringBuilder("13500"),
            new StringBuilder("988/989 г."),
            new StringBuilder("Освободить сына"),
            new StringBuilder("Владимир"),
            new StringBuilder("Владимир"),
            new StringBuilder("1007 г."),
            new StringBuilder("1004 г."),
            new StringBuilder("986-988 гг."),
            new StringBuilder("Булгаров"),
            new StringBuilder("983 г."),
            new StringBuilder("1001 г."),
            new StringBuilder("999 г."),
            new StringBuilder("993 г."),
            new StringBuilder("985 г."),
            new StringBuilder("1010 г."),
            new StringBuilder("Кирилл I Грек"),
            new StringBuilder("999 г."),
            new StringBuilder("Хорваты"),
            new StringBuilder("2"),
            new StringBuilder("Ярослав"),
            new StringBuilder("Позвизд")
    };

    public Question4() {}
}