package studio.rashka.Test;

public class Question2 {

    public StringBuilder[] V2 = new StringBuilder[]{
            new StringBuilder("853 год"),
            new StringBuilder("862-879 гг."),
            new StringBuilder("1119 году"),
            new StringBuilder("3"),
            new StringBuilder("Кирилл"),
            new StringBuilder("Меха"),
            new StringBuilder("Купцами"),
            new StringBuilder("жена дворянина"),
            new StringBuilder("одежда купца"),
            new StringBuilder("907 году"),
            new StringBuilder("823-и годы"),
            new StringBuilder("1121 году"),
            new StringBuilder("Любеч"),
            new StringBuilder("XI"),
            new StringBuilder("Князь Рюрик"),
            new StringBuilder("1158"),
            new StringBuilder("Святославом"),
            new StringBuilder("родовое земельное владение"),
            new StringBuilder("Вячеслав"),
            new StringBuilder("963-1042"),
            new StringBuilder("992-1032"),
            new StringBuilder("1024-1078"),
            new StringBuilder("1048-1060"),
            new StringBuilder("1020-1083"),
            new StringBuilder("1072-1075 и 1077-1091"),
            new StringBuilder("855-912"),
            new StringBuilder("877-915"),
            new StringBuilder("872 году"),
            new StringBuilder("рабочий скот"),
            new StringBuilder("1109 году"),
            new StringBuilder("Дружинниками"),
            new StringBuilder("Феодала"),
            new StringBuilder("Закуп"),
            new StringBuilder("Воны"),
            new StringBuilder("1107 году"),
            new StringBuilder("народный праздник"),
            new StringBuilder("имущество"),
            new StringBuilder("Класс феодалов"),
            new StringBuilder("1183 году"),
            new StringBuilder("1172 году"),
            new StringBuilder("1209 году"),
            new StringBuilder("Холоп"),
            new StringBuilder("1242 год"),
            new StringBuilder("XV"),
            new StringBuilder("Народное собрание"),
            new StringBuilder("965 год"),
            new StringBuilder("968 год"),
            new StringBuilder("875-893 гг."),
            new StringBuilder("865 год"),
            new StringBuilder("Парусно-весельное судно"),
            new StringBuilder("Воры"),
            new StringBuilder("885 год"),
            new StringBuilder("выкуп земли"),
            new StringBuilder("907 году"),
            new StringBuilder("918 году"),
            new StringBuilder("Отарица"),
            new StringBuilder("962 году"),
            new StringBuilder("Константинополь"),
            new StringBuilder("912-966"),
            new StringBuilder("Изяславу"),
            new StringBuilder("975 году"),
            new StringBuilder("978 год"),
            new StringBuilder("Дружба"),
            new StringBuilder("1053 год"),
            new StringBuilder("Рюрик"),
            new StringBuilder("Боняк"),
            new StringBuilder("1139 год"),
            new StringBuilder("Ладья"),
            new StringBuilder("Поляне"),
            new StringBuilder("Дреговичи"),
            new StringBuilder("Средний Днепр"),
            new StringBuilder("Река Припять"),
            new StringBuilder("Средний Днестр"),
            new StringBuilder("Верховья Буга"),
            new StringBuilder("Река Днепр"),
            new StringBuilder("Правобережье Днепра"),
            new StringBuilder("Верховья Буга"),
            new StringBuilder("980 год"),
            new StringBuilder("Средний Прут"),
            new StringBuilder("Правобережье Днестра"),
            new StringBuilder("1303 год"),
            new StringBuilder("Изборск"),
            new StringBuilder("IX-X"),
            new StringBuilder("969 год"),
            new StringBuilder("Волок"),
            new StringBuilder("880 год"),
            new StringBuilder("Ткань"),
            new StringBuilder("983 год"),
            new StringBuilder("Самкерц"),
            new StringBuilder("Кирилл"),
            new StringBuilder("938 год"),
            new StringBuilder("Войско для защиты"),
            new StringBuilder("965 год"),
            new StringBuilder("С Византией"),
            new StringBuilder("Каганы"),
            new StringBuilder("Подросток"),
            new StringBuilder("Всеволода"),
            new StringBuilder("Германо-русский"),
            new StringBuilder("Из-за женщины"),
            new StringBuilder("986 год"),
            new StringBuilder("Ятваги"),
            new StringBuilder("981 году"),
            new StringBuilder("Изяслав"),
            new StringBuilder("Византию"),
            new StringBuilder("991-996"),
            new StringBuilder("Лубна"),
            new StringBuilder("989 год"),
            new StringBuilder("1008 году"),
            new StringBuilder("1001 год"),
            new StringBuilder("994 год"),
            new StringBuilder("998 год"),
            new StringBuilder("1018 год"),
            new StringBuilder("церкви"),
            new StringBuilder("Пруссы"),
            new StringBuilder("Тризна"),
            new StringBuilder("864-866 гг."),
            new StringBuilder("племя"),
            new StringBuilder("город"),
            new StringBuilder("855 г."),
            new StringBuilder("864 г."),
            new StringBuilder("864 г."),
            new StringBuilder("860 г."),
            new StringBuilder("Ладоге"),
            new StringBuilder("868 г."),
            new StringBuilder("868 г."),
            new StringBuilder("864 г."),
            new StringBuilder("Синеус"),
            new StringBuilder("Дядей"),
            new StringBuilder("869 г."),
            new StringBuilder("865 г."),
            new StringBuilder("855 г."),
            new StringBuilder("877 г."),
            new StringBuilder("873 г."),
            new StringBuilder("Рюрик"),
            new StringBuilder("Ростов"),
            new StringBuilder("Игорь"),
            new StringBuilder("877 г."),
            new StringBuilder("Ярослав"),
            new StringBuilder("Епископ"),
            new StringBuilder("Синеус"),
            new StringBuilder("Аскольд"),
            new StringBuilder("853 г."),
            new StringBuilder("868 г."),
            new StringBuilder("Белозеро"),
            new StringBuilder("Новгород"),
            new StringBuilder("872 г."),
            new StringBuilder("888 г."),
            new StringBuilder("907 г."),
            new StringBuilder("903 г."),
            new StringBuilder("Ладога"),
            new StringBuilder("Игорю"),
            new StringBuilder("Древлян"),
            new StringBuilder("Радимичей"),
            new StringBuilder("Кривичей"),
            new StringBuilder("Весь"),
            new StringBuilder("Гуж"),
            new StringBuilder("899 г."),
            new StringBuilder("по 8 гривен"),
            new StringBuilder("от болезни"),
            new StringBuilder("882 г."),
            new StringBuilder("908-941 гг."),
            new StringBuilder("Всеволод"),
            new StringBuilder("Елена"),
            new StringBuilder("Святослав"),
            new StringBuilder("Киев"),
            new StringBuilder("906 г."),
            new StringBuilder("920 г."),
            new StringBuilder("Возложил дань"),
            new StringBuilder("Древлянам"),
            new StringBuilder("903 г."),
            new StringBuilder("925 г."),
            new StringBuilder("Печенег"),
            new StringBuilder("937-939 гг."),
            new StringBuilder("Москву"),
            new StringBuilder("942-943 гг."),
            new StringBuilder("942 г."),
            new StringBuilder("в 15 лет"),
            new StringBuilder("Тиверцев"),
            new StringBuilder("Войска против Игоря"),
            new StringBuilder("950 г."),
            new StringBuilder("2"),
            new StringBuilder("936 г."),
            new StringBuilder("935 г."),
            new StringBuilder("950-960 гг."),
            new StringBuilder("920-969 гг."),
            new StringBuilder("2 раза"),
            new StringBuilder("937 г."),
            new StringBuilder("Игорь"),
            new StringBuilder("945 г."),
            new StringBuilder("952 г."),
            new StringBuilder("Новгород"),
            new StringBuilder("Анна"),
            new StringBuilder("957 г."),
            new StringBuilder("Далмаций"),
            new StringBuilder("940-945 гг."),
            new StringBuilder("Москва"),
            new StringBuilder("942-972 гг."),
            new StringBuilder("943-961 гг."),
            new StringBuilder("941-962 гг."),
            new StringBuilder("Олег"),
            new StringBuilder("Святослав"),
            new StringBuilder("942 год"),
            new StringBuilder("Ярополк"),
            new StringBuilder("Хижина"),
            new StringBuilder("Лодка"),
            new StringBuilder("Летопись"),
            new StringBuilder("Печка"),
            new StringBuilder("VII век"),
            new StringBuilder("Язычество"),
            new StringBuilder("951 год"),
            new StringBuilder("Конрад I"),
            new StringBuilder("964 год"),
            new StringBuilder("Святослав"),
            new StringBuilder("958 год"),
            new StringBuilder("955 год"),
            new StringBuilder("969 год"),
            new StringBuilder("965 год"),
            new StringBuilder("960/961 год"),
            new StringBuilder("961/962 год"),
            new StringBuilder("969 год"),
            new StringBuilder("970-971 гг."),
            new StringBuilder("963 год"),
            new StringBuilder("957 год"),
            new StringBuilder("Иоанн I Цимисхий"),
            new StringBuilder("969 год"),
            new StringBuilder("Оружие"),
            new StringBuilder("962 год"),
            new StringBuilder("975 год"),
            new StringBuilder("971 год"),
            new StringBuilder("Угольная руда"),
            new StringBuilder("961-966 гг."),
            new StringBuilder("420 кг"),
            new StringBuilder("968-969 гг."),
            new StringBuilder("967 год"),
            new StringBuilder("Печенеги"),
            new StringBuilder("976 год"),
            new StringBuilder("Иоаннополис"),
            new StringBuilder("Коловрату"),
            new StringBuilder("1"),
            new StringBuilder("Олег"),
            new StringBuilder("988 год"),
            new StringBuilder("961 год"),
            new StringBuilder("Ярополк"),
            new StringBuilder("1020 год"),
            new StringBuilder("Сфенга"),
            new StringBuilder("Василий Болгаробойца"),
            new StringBuilder("947-960 гг."),
            new StringBuilder("Игорь"),
            new StringBuilder("972-978 гг."),
            new StringBuilder("Раздел власти"),
            new StringBuilder("961-970 гг."),
            new StringBuilder("Приемник"),
            new StringBuilder("970 г."),
            new StringBuilder("967 г."),
            new StringBuilder("Новгородские"),
            new StringBuilder("Древлянские"),
            new StringBuilder("Ярополк"),
            new StringBuilder("966 г."),
            new StringBuilder("Москва"),
            new StringBuilder("Олег"),
            new StringBuilder("Кунигунда"),
            new StringBuilder("Олег"),
            new StringBuilder("Ита"),
            new StringBuilder("молоток"),
            new StringBuilder("Ярополк"),
            new StringBuilder("969 г."),
            new StringBuilder("Суздаль"),
            new StringBuilder("Пойман и казнен"),
            new StringBuilder("Бежал"),
            new StringBuilder("973 г."),
            new StringBuilder("Словене"),
            new StringBuilder("Отрок Варяжко"),
            new StringBuilder("Родень"),
            new StringBuilder("Герцог"),
            new StringBuilder("Боярин"),
            new StringBuilder("Сжег"),
            new StringBuilder("960-1015 гг."),
            new StringBuilder("962-988 гг."),
            new StringBuilder("969-1007 гг."),
            new StringBuilder("Подарок орды"),
            new StringBuilder("Крещение Руси"),
            new StringBuilder("964 г."),
            new StringBuilder("Ярослав"),
            new StringBuilder("Киев"),
            new StringBuilder("Малуша"),
            new StringBuilder("Олаф"),
            new StringBuilder("Свенельд"),
            new StringBuilder("Елизавета"),
            new StringBuilder("Убил их"),
            new StringBuilder("Елизавета"),
            new StringBuilder("Малуше"),
            new StringBuilder("черный рынок"),
            new StringBuilder("алтарь"),
            new StringBuilder("церковь"),
            new StringBuilder("Полоцк"),
            new StringBuilder("Хорс"),
            new StringBuilder("Хорс"),
            new StringBuilder("Перун"),
            new StringBuilder("Хорс"),
            new StringBuilder("Перун"),
            new StringBuilder("Мокошь"),
            new StringBuilder("Дажьбог"),
            new StringBuilder("500"),
            new StringBuilder("вспахивание поля"),
            new StringBuilder("3"),
            new StringBuilder("пивовар"),
            new StringBuilder("Игумен"),
            new StringBuilder("Игумен"),
            new StringBuilder("Игумен"),
            new StringBuilder("Игумен"),
            new StringBuilder("Игумен"),
            new StringBuilder("Постриг"),
            new StringBuilder("Чтец"),
            new StringBuilder("Постриг"),
            new StringBuilder("Пономарь"),
            new StringBuilder("Белец"),
            new StringBuilder("вход в храм"),
            new StringBuilder("983 г."),
            new StringBuilder("Наложницы"),
            new StringBuilder("Игорь"),
            new StringBuilder("987/988 г."),
            new StringBuilder("978 г."),
            new StringBuilder("Константин VIII"),
            new StringBuilder("994 г."),
            new StringBuilder("Абидос"),
            new StringBuilder("4000"),
            new StringBuilder("970 г."),
            new StringBuilder("Центр торговли"),
            new StringBuilder("Новгород"),
            new StringBuilder("Василий II"),
            new StringBuilder("992/993 г."),
            new StringBuilder("987 г."),
            new StringBuilder("981-982 гг."),
            new StringBuilder("Ятвягов"),
            new StringBuilder("974 г."),
            new StringBuilder("988 г."),
            new StringBuilder("984 г."),
            new StringBuilder("980 г."),
            new StringBuilder("969 г."),
            new StringBuilder("991 г."),
            new StringBuilder("Илларион"),
            new StringBuilder("986 г."),
            new StringBuilder("Радимичи"),
            new StringBuilder("8"),
            new StringBuilder("Святополк"),
            new StringBuilder("Судислав")
    };

    public Question2() {}
}