package studio.rashka.Test;

public class Question3 {

    public StringBuilder[] V3 = new StringBuilder[]{
            new StringBuilder("860 год"),
            new StringBuilder("862-870 гг."),
            new StringBuilder("1124 году"),
            new StringBuilder("4"),
            new StringBuilder("Гаральд"),
            new StringBuilder("Золото"),
            new StringBuilder("Земледельцами"),
            new StringBuilder("землепашец"),
            new StringBuilder("крепкий напиток"),
            new StringBuilder("905 году"),
            new StringBuilder("830-е годы"),
            new StringBuilder("1132 году"),
            new StringBuilder("Чернигове"),
            new StringBuilder("IX"),
            new StringBuilder("Князь Мстислав"),
            new StringBuilder("1147"),
            new StringBuilder("Всеволодом"),
            new StringBuilder("бояре при князе"),
            new StringBuilder("Ротислав"),
            new StringBuilder("972-1047"),
            new StringBuilder("1023-1054"),
            new StringBuilder("1047-1088"),
            new StringBuilder("1054-1078"),
            new StringBuilder("1033-1095"),
            new StringBuilder("1075-1091"),
            new StringBuilder("860-913"),
            new StringBuilder("879-912"),
            new StringBuilder("875 году"),
            new StringBuilder("охотничья ловушка"),
            new StringBuilder("1100 году"),
            new StringBuilder("Феодалами"),
            new StringBuilder("Бояря"),
            new StringBuilder("Холоп"),
            new StringBuilder("Куны"),
            new StringBuilder("1110 году"),
            new StringBuilder("народное восстание"),
            new StringBuilder("летописец"),
            new StringBuilder("Класс рядовичей"),
            new StringBuilder("1187 году"),
            new StringBuilder("1164 году"),
            new StringBuilder("1203 году"),
            new StringBuilder("Изгой"),
            new StringBuilder("1329 год"),
            new StringBuilder("XI"),
            new StringBuilder("Заключение договора"),
            new StringBuilder("968 год"),
            new StringBuilder("982 год"),
            new StringBuilder("888-1025 гг."),
            new StringBuilder("870 год"),
            new StringBuilder("Коромысло"),
            new StringBuilder("Славянские племена"),
            new StringBuilder("883 год"),
            new StringBuilder("выкуп скота"),
            new StringBuilder("904 году"),
            new StringBuilder("915 году"),
            new StringBuilder("Проводы"),
            new StringBuilder("950 году"),
            new StringBuilder("Киев"),
            new StringBuilder("915-969"),
            new StringBuilder("Всеволоду"),
            new StringBuilder("982 году"),
            new StringBuilder("984 год"),
            new StringBuilder("Ссора"),
            new StringBuilder("1057 год"),
            new StringBuilder("Всеволод"),
            new StringBuilder("Гзак"),
            new StringBuilder("1136 год"),
            new StringBuilder("Сахо"),
            new StringBuilder("Дулебы"),
            new StringBuilder("Тиверцы"),
            new StringBuilder("Реки Стырь и Горынь"),
            new StringBuilder("Правобережье Днепра"),
            new StringBuilder("Южный Буг"),
            new StringBuilder("Средний Днестр"),
            new StringBuilder("Река Припять"),
            new StringBuilder("Верховья Буга"),
            new StringBuilder("Правобережье Днепра"),
            new StringBuilder("984 год"),
            new StringBuilder("Средний Днепр"),
            new StringBuilder("Правобережье Прута"),
            new StringBuilder("1309 год"),
            new StringBuilder("Куковка"),
            new StringBuilder("V-VII"),
            new StringBuilder("973 год"),
            new StringBuilder("Острог"),
            new StringBuilder("885 год"),
            new StringBuilder("Древесина"),
            new StringBuilder("979 год"),
            new StringBuilder("Киммерик"),
            new StringBuilder("Святослав"),
            new StringBuilder("941 год"),
            new StringBuilder("Убежище"),
            new StringBuilder("968 год"),
            new StringBuilder("С Русской дружиной"),
            new StringBuilder("Византия"),
            new StringBuilder("Мужчина"),
            new StringBuilder("Изяслава"),
            new StringBuilder("Германо-византийский"),
            new StringBuilder("Не поделили землю"),
            new StringBuilder("989 год"),
            new StringBuilder("Уличи"),
            new StringBuilder("985 году"),
            new StringBuilder("Всеволод"),
            new StringBuilder("Германию"),
            new StringBuilder("995-998"),
            new StringBuilder("Киев"),
            new StringBuilder("1002 год"),
            new StringBuilder("1012 году"),
            new StringBuilder("1009 год"),
            new StringBuilder("1003 год"),
            new StringBuilder("1005 год"),
            new StringBuilder("1021 год"),
            new StringBuilder("дома бояр"),
            new StringBuilder("Поляки"),
            new StringBuilder("Сахо"),
            new StringBuilder("861 г."),
            new StringBuilder("изгнанник"),
            new StringBuilder("деревня"),
            new StringBuilder("859 г."),
            new StringBuilder("868 г."),
            new StringBuilder("868 г."),
            new StringBuilder("864 г."),
            new StringBuilder("Новгороде"),
            new StringBuilder("870 г."),
            new StringBuilder("873 г."),
            new StringBuilder("868 г."),
            new StringBuilder("Гостомысл"),
            new StringBuilder("Сыном"),
            new StringBuilder("874 г."),
            new StringBuilder("869 г."),
            new StringBuilder("863 г."),
            new StringBuilder("880 г."),
            new StringBuilder("876 г."),
            new StringBuilder("Дир"),
            new StringBuilder("Киев"),
            new StringBuilder("Святослав"),
            new StringBuilder("881 г."),
            new StringBuilder("Святополк"),
            new StringBuilder("Феодал"),
            new StringBuilder("Аскольд"),
            new StringBuilder("Трувор"),
            new StringBuilder("858 г."),
            new StringBuilder("871 г."),
            new StringBuilder("Византия"),
            new StringBuilder("Изборск"),
            new StringBuilder("875 г."),
            new StringBuilder("892 г."),
            new StringBuilder("911 г."),
            new StringBuilder("907 г."),
            new StringBuilder("Смоленск"),
            new StringBuilder("Святославу"),
            new StringBuilder("Кривичей"),
            new StringBuilder("Северян"),
            new StringBuilder("Северян"),
            new StringBuilder("Гуж"),
            new StringBuilder("Ладья"),
            new StringBuilder("907 г."),
            new StringBuilder("по 10 гривен"),
            new StringBuilder("в сражении"),
            new StringBuilder("893 г."),
            new StringBuilder("912-945 гг."),
            new StringBuilder("Ярослав"),
            new StringBuilder("Анна"),
            new StringBuilder("Олег"),
            new StringBuilder("Псков"),
            new StringBuilder("910 г."),
            new StringBuilder("924 г."),
            new StringBuilder("Продал в рабство"),
            new StringBuilder("Византии"),
            new StringBuilder("909 г."),
            new StringBuilder("928 г."),
            new StringBuilder("Византии"),
            new StringBuilder("941-944 гг."),
            new StringBuilder("Византию"),
            new StringBuilder("945-948 гг."),
            new StringBuilder("948 г."),
            new StringBuilder("в 18 лет"),
            new StringBuilder("Кривичей"),
            new StringBuilder("Дочь в жены"),
            new StringBuilder("954 г."),
            new StringBuilder("3"),
            new StringBuilder("941 г."),
            new StringBuilder("939 г."),
            new StringBuilder("953-959 гг."),
            new StringBuilder("924-963 гг."),
            new StringBuilder("4 раза"),
            new StringBuilder("942 г."),
            new StringBuilder("Ярослав"),
            new StringBuilder("951 г."),
            new StringBuilder("955 г."),
            new StringBuilder("Киев"),
            new StringBuilder("Маргарита"),
            new StringBuilder("963 г."),
            new StringBuilder("Константин VII"),
            new StringBuilder("942 г."),
            new StringBuilder("Константинополь"),
            new StringBuilder("943-975 гг."),
            new StringBuilder("945-972 гг."),
            new StringBuilder("943-970 гг."),
            new StringBuilder("Владимир"),
            new StringBuilder("Ярополк"),
            new StringBuilder("945 год"),
            new StringBuilder("Елена"),
            new StringBuilder("Топорик"),
            new StringBuilder("Домик у реки"),
            new StringBuilder("Лодка"),
            new StringBuilder("Придворный"),
            new StringBuilder("VI век"),
            new StringBuilder("Анимизм"),
            new StringBuilder("959 год"),
            new StringBuilder("Карл III Толстый"),
            new StringBuilder("969 год"),
            new StringBuilder("Изяслав"),
            new StringBuilder("964 год"),
            new StringBuilder("960 год"),
            new StringBuilder("973 год"),
            new StringBuilder("969 год"),
            new StringBuilder("968/969 год"),
            new StringBuilder("965 год"),
            new StringBuilder("973 год"),
            new StringBuilder("972-974 гг."),
            new StringBuilder("967/968 год"),
            new StringBuilder("963 год"),
            new StringBuilder("Болгары"),
            new StringBuilder("974 год"),
            new StringBuilder("Хлеб"),
            new StringBuilder("968 год"),
            new StringBuilder("978/979 год"),
            new StringBuilder("975 год"),
            new StringBuilder("Весовая мера"),
            new StringBuilder("965 год"),
            new StringBuilder("385 кг"),
            new StringBuilder("972-974 гг."),
            new StringBuilder("970 год"),
            new StringBuilder("Болгары"),
            new StringBuilder("981 год"),
            new StringBuilder("Бургас"),
            new StringBuilder("Свенельду"),
            new StringBuilder("2"),
            new StringBuilder("Ярополк"),
            new StringBuilder("994 год"),
            new StringBuilder("968 год"),
            new StringBuilder("Святослав"),
            new StringBuilder("1024 год"),
            new StringBuilder("Ярополк"),
            new StringBuilder("Георгий Цула"),
            new StringBuilder("952-981 гг."),
            new StringBuilder("Ярополк"),
            new StringBuilder("975-977 гг."),
            new StringBuilder("Приемник"),
            new StringBuilder("972-976 гг."),
            new StringBuilder("Брак с княгиней"),
            new StringBuilder("974 г."),
            new StringBuilder("972 г."),
            new StringBuilder("Киевские"),
            new StringBuilder("Киевские"),
            new StringBuilder("Владимир"),
            new StringBuilder("973 г."),
            new StringBuilder("Киев"),
            new StringBuilder("Ярополк"),
            new StringBuilder("Ита"),
            new StringBuilder("Ярополк"),
            new StringBuilder("Кунигунда"),
            new StringBuilder("рубанок"),
            new StringBuilder("Святослав"),
            new StringBuilder("977 г."),
            new StringBuilder("Киев"),
            new StringBuilder("Пойман и повешен"),
            new StringBuilder("Помог Олегу"),
            new StringBuilder("978 г."),
            new StringBuilder("Кривичи"),
            new StringBuilder("Монах Иаков"),
            new StringBuilder("Киев"),
            new StringBuilder("Воевода"),
            new StringBuilder("Воевода"),
            new StringBuilder("Продал"),
            new StringBuilder("966-1010 гг."),
            new StringBuilder("970-988 гг."),
            new StringBuilder("974-1012 гг."),
            new StringBuilder("Приемник"),
            new StringBuilder("Пожар в Киеве"),
            new StringBuilder("988 г."),
            new StringBuilder("Игорь"),
            new StringBuilder("Москва"),
            new StringBuilder("Елизавета"),
            new StringBuilder("Добрыня"),
            new StringBuilder("Трюггви Олафссон"),
            new StringBuilder("Малуша"),
            new StringBuilder("Отправил в Киев"),
            new StringBuilder("Рогнеда"),
            new StringBuilder("Елизавете"),
            new StringBuilder("собрание дворян"),
            new StringBuilder("виселица"),
            new StringBuilder("языческий храм"),
            new StringBuilder("Смоленск"),
            new StringBuilder("Стрибог"),
            new StringBuilder("Велес"),
            new StringBuilder("Дажьбог"),
            new StringBuilder("Перун"),
            new StringBuilder("Велес"),
            new StringBuilder("Хорс"),
            new StringBuilder("Велес"),
            new StringBuilder("650"),
            new StringBuilder("водяная мельница"),
            new StringBuilder("5"),
            new StringBuilder("монах"),
            new StringBuilder("Рясофор"),
            new StringBuilder("Схима"),
            new StringBuilder("Рясофор"),
            new StringBuilder("Послушник"),
            new StringBuilder("Рясофор"),
            new StringBuilder("Рясофор"),
            new StringBuilder("Белец"),
            new StringBuilder("Свещеносец"),
            new StringBuilder("Свещеносец"),
            new StringBuilder("Куколь"),
            new StringBuilder("часть ружья"),
            new StringBuilder("987/988 г."),
            new StringBuilder("Орда"),
            new StringBuilder("Ярополк"),
            new StringBuilder("992 г."),
            new StringBuilder("988 г."),
            new StringBuilder("Василий II"),
            new StringBuilder("1000 г."),
            new StringBuilder("Киев"),
            new StringBuilder("6000"),
            new StringBuilder("979 г."),
            new StringBuilder("Захват власти"),
            new StringBuilder("Суздаль"),
            new StringBuilder("Добрыня"),
            new StringBuilder("1002 г."),
            new StringBuilder("995 г."),
            new StringBuilder("984-985 гг."),
            new StringBuilder("Вятичей"),
            new StringBuilder("980 г."),
            new StringBuilder("995 г."),
            new StringBuilder("990 г."),
            new StringBuilder("985 г."),
            new StringBuilder("978 г."),
            new StringBuilder("999 г."),
            new StringBuilder("Феофилакт"),
            new StringBuilder("992 г."),
            new StringBuilder("Ятвяги"),
            new StringBuilder("4"),
            new StringBuilder("Борис"),
            new StringBuilder("Ярослав")
    };

    public Question3() {}
}