package studio.rashka.Test;

public class Question1 {

    public StringBuilder[] V1 = new StringBuilder[]{
            new StringBuilder("862 год"),
            new StringBuilder("858-860 гг."),
            new StringBuilder("1108 году"),
            new StringBuilder("2"),
            new StringBuilder("Сильвестр"),
            new StringBuilder("Древние летописи"),
            new StringBuilder("Боярами"),
            new StringBuilder("жена крестьянина"),
            new StringBuilder("пахотное орудие"),
            new StringBuilder("912 году"),
            new StringBuilder("845-е годы"),
            new StringBuilder("1105 году"),
            new StringBuilder("Москве"),
            new StringBuilder("XII"),
            new StringBuilder("Князь Олег"),
            new StringBuilder("1143"),
            new StringBuilder("Ярополком"),
            new StringBuilder("небольшой отряд солдат"),
            new StringBuilder("Святослав"),
            new StringBuilder("954-1037"),
            new StringBuilder("1016-1054"),
            new StringBuilder("1024-1065"),
            new StringBuilder("1054-1068"),
            new StringBuilder("1025-1090"),
            new StringBuilder("1076-1077 и 1078-1093"),
            new StringBuilder("850-910"),
            new StringBuilder("875-910"),
            new StringBuilder("869 году"),
            new StringBuilder("дворовые слуги"),
            new StringBuilder("1083 году"),
            new StringBuilder("Рабами"),
            new StringBuilder("Раба"),
            new StringBuilder("Челядь"),
            new StringBuilder("Рубли"),
            new StringBuilder("1103 году"),
            new StringBuilder("денежный сбор с крестьян"),
            new StringBuilder("денежный сбор"),
            new StringBuilder("Класс дружины"),
            new StringBuilder("1196 году"),
            new StringBuilder("1169 году"),
            new StringBuilder("1205 году"),
            new StringBuilder("Челядь"),
            new StringBuilder("1209 год"),
            new StringBuilder("XII"),
            new StringBuilder("Государственный переворот"),
            new StringBuilder("961 год"),
            new StringBuilder("999 год"),
            new StringBuilder("875-1036 гг."),
            new StringBuilder("860 год"),
            new StringBuilder("Военное построение"),
            new StringBuilder("Племена изгоев"),
            new StringBuilder("890 год"),
            new StringBuilder("свобода от рабства"),
            new StringBuilder("912 году"),
            new StringBuilder("921 году"),
            new StringBuilder("Обряд"),
            new StringBuilder("955 году"),
            new StringBuilder("Москва"),
            new StringBuilder("910-977"),
            new StringBuilder("Олегу"),
            new StringBuilder("977 году"),
            new StringBuilder("988 год"),
            new StringBuilder("Убийство"),
            new StringBuilder("1050 год"),
            new StringBuilder("Ярополк"),
            new StringBuilder("Башкорд"),
            new StringBuilder("1141 год"),
            new StringBuilder("Отарица"),
            new StringBuilder("Уличи"),
            new StringBuilder("Северяне"),
            new StringBuilder("Средний Днестр"),
            new StringBuilder("Река Горынь"),
            new StringBuilder("Средний Днепр"),
            new StringBuilder("Левобережье Днепра"),
            new StringBuilder("Река Днестр"),
            new StringBuilder("Левобережье Десны"),
            new StringBuilder("Верховья Прута"),
            new StringBuilder("974 год"),
            new StringBuilder("Средний Буг"),
            new StringBuilder("Правобережье Днепра"),
            new StringBuilder("1298 год"),
            new StringBuilder("Труворов"),
            new StringBuilder("VII"),
            new StringBuilder("965 год"),
            new StringBuilder("Куковка"),
            new StringBuilder("873 год"),
            new StringBuilder("Уголь"),
            new StringBuilder("988 год"),
            new StringBuilder("Нимфей"),
            new StringBuilder("Олег"),
            new StringBuilder("Разорила и ушла"),
            new StringBuilder("Епископа для Руси"),
            new StringBuilder("961 год"),
            new StringBuilder("С уличами"),
            new StringBuilder("Уличи"),
            new StringBuilder("Младенец"),
            new StringBuilder("Святослава"),
            new StringBuilder("Русско-византийский"),
            new StringBuilder("Из-за трона"),
            new StringBuilder("983 год"),
            new StringBuilder("Каганы"),
            new StringBuilder("972 году"),
            new StringBuilder("Олег"),
            new StringBuilder("Половцев"),
            new StringBuilder("991-993"),
            new StringBuilder("Белгород"),
            new StringBuilder("984 год"),
            new StringBuilder("1000 году"),
            new StringBuilder("988 год"),
            new StringBuilder("983 год"),
            new StringBuilder("993 год"),
            new StringBuilder("1013 год"),
            new StringBuilder("замок князя"),
            new StringBuilder("Словаки"),
            new StringBuilder("Отарица"),
            new StringBuilder("860-862 гг."),
            new StringBuilder("стая"),
            new StringBuilder("замок"),
            new StringBuilder("852 г."),
            new StringBuilder("862 г."),
            new StringBuilder("860 г."),
            new StringBuilder("855 г."),
            new StringBuilder("Царьграде"),
            new StringBuilder("864 г."),
            new StringBuilder("864 г."),
            new StringBuilder("860 г."),
            new StringBuilder("Трувор"),
            new StringBuilder("Двоюродным братом"),
            new StringBuilder("865 г."),
            new StringBuilder("861 г."),
            new StringBuilder("850 г."),
            new StringBuilder("873 г."),
            new StringBuilder("869 г."),
            new StringBuilder("Гостомысл"),
            new StringBuilder("Ладога"),
            new StringBuilder("Николай"),
            new StringBuilder("873 г."),
            new StringBuilder("Игорь"),
            new StringBuilder("Посадник"),
            new StringBuilder("Дир"),
            new StringBuilder("Дир"),
            new StringBuilder("849 г."),
            new StringBuilder("864 г."),
            new StringBuilder("Новгород"),
            new StringBuilder("Киев"),
            new StringBuilder("868 г."),
            new StringBuilder("882 г."),
            new StringBuilder("901 г."),
            new StringBuilder("899 г."),
            new StringBuilder("Киев"),
            new StringBuilder("Олегу"),
            new StringBuilder("Северян"),
            new StringBuilder("Кривичей"),
            new StringBuilder("Варягов"),
            new StringBuilder("Уключина"),
            new StringBuilder("Весь"),
            new StringBuilder("892 г."),
            new StringBuilder("по 6 гривен"),
            new StringBuilder("от укуса змеи"),
            new StringBuilder("878 г."),
            new StringBuilder("904-923 гг."),
            new StringBuilder("Святослав"),
            new StringBuilder("Ольга"),
            new StringBuilder("Всеволод"),
            new StringBuilder("Москва"),
            new StringBuilder("902 г."),
            new StringBuilder("914 г."),
            new StringBuilder("Повесил бояр"),
            new StringBuilder("Печенегам"),
            new StringBuilder("900 г."),
            new StringBuilder("920 г."),
            new StringBuilder("Древлян"),
            new StringBuilder("937 г."),
            new StringBuilder("Печенег"),
            new StringBuilder("941-944 гг."),
            new StringBuilder("937 г."),
            new StringBuilder("в 3 года"),
            new StringBuilder("Печенег"),
            new StringBuilder("Сбежал"),
            new StringBuilder("944 г."),
            new StringBuilder("1"),
            new StringBuilder("927 г."),
            new StringBuilder("928 г."),
            new StringBuilder("945-960 гг."),
            new StringBuilder("920-962 гг."),
            new StringBuilder("1 раз"),
            new StringBuilder("931 г."),
            new StringBuilder("Ольга"),
            new StringBuilder("941 г."),
            new StringBuilder("947 г."),
            new StringBuilder("Москва"),
            new StringBuilder("Елена"),
            new StringBuilder("951 г."),
            new StringBuilder("Ганнибалиан"),
            new StringBuilder("940-942 гг."),
            new StringBuilder("Киев"),
            new StringBuilder("938-977 гг."),
            new StringBuilder("940-955 гг."),
            new StringBuilder("941-953 гг."),
            new StringBuilder("Святослав"),
            new StringBuilder("Олег"),
            new StringBuilder("939 год"),
            new StringBuilder("Святослав"),
            new StringBuilder("Лодка"),
            new StringBuilder("Участок земли"),
            new StringBuilder("Памятник"),
            new StringBuilder("Сторожевая башня"),
            new StringBuilder("VIII век"),
            new StringBuilder("Христианство"),
            new StringBuilder("947 год"),
            new StringBuilder("Генрих I"),
            new StringBuilder("961 год"),
            new StringBuilder("Ярополк"),
            new StringBuilder("952 год"),
            new StringBuilder("949 год"),
            new StringBuilder("965 год"),
            new StringBuilder("961 год"),
            new StringBuilder("954 год"),
            new StringBuilder("955/956 год"),
            new StringBuilder("966 год"),
            new StringBuilder("966-968 гг."),
            new StringBuilder("958 год"),
            new StringBuilder("952 год"),
            new StringBuilder("Печенеги"),
            new StringBuilder("966 год"),
            new StringBuilder("Золото"),
            new StringBuilder("957 год"),
            new StringBuilder("971 год"),
            new StringBuilder("967 год"),
            new StringBuilder("Повозка заключенных"),
            new StringBuilder("958-960 гг."),
            new StringBuilder("455 кг"),
            new StringBuilder("966 год"),
            new StringBuilder("962 год"),
            new StringBuilder("Венгры"),
            new StringBuilder("970 год"),
            new StringBuilder("Пловдив"),
            new StringBuilder("Склиру"),
            new StringBuilder("Бездетный"),
            new StringBuilder("Владимир"),
            new StringBuilder("982 год"),
            new StringBuilder("955 год"),
            new StringBuilder("Олег"),
            new StringBuilder("1016 год"),
            new StringBuilder("Святослав"),
            new StringBuilder("Андроник Дука"),
            new StringBuilder("942-967 гг."),
            new StringBuilder("Святослав"),
            new StringBuilder("962-968 гг."),
            new StringBuilder("Захватил власть"),
            new StringBuilder("955-957 гг."),
            new StringBuilder("Захватил власть"),
            new StringBuilder("963 г."),
            new StringBuilder("963 г."),
            new StringBuilder("Суздальские"),
            new StringBuilder("Новгородские"),
            new StringBuilder("Олег"),
            new StringBuilder("961 г."),
            new StringBuilder("Константинополь"),
            new StringBuilder("Владимир"),
            new StringBuilder("Куно"),
            new StringBuilder("Владимир"),
            new StringBuilder("Юдит"),
            new StringBuilder("рисунок"),
            new StringBuilder("Игорь"),
            new StringBuilder("961 г."),
            new StringBuilder("Родень"),
            new StringBuilder("Задавлен лошадьми"),
            new StringBuilder("Бездействовал"),
            new StringBuilder("966 г."),
            new StringBuilder("Пруссы"),
            new StringBuilder("Воевода Блуд"),
            new StringBuilder("Новгород"),
            new StringBuilder("Князь"),
            new StringBuilder("Монах"),
            new StringBuilder("Крестил"),
            new StringBuilder("956-1001 гг."),
            new StringBuilder("958-988 гг."),
            new StringBuilder("968-1010 гг."),
            new StringBuilder("Захватил престол"),
            new StringBuilder("Мир с Византией"),
            new StringBuilder("955 г."),
            new StringBuilder("Ярополк"),
            new StringBuilder("с. Будутино"),
            new StringBuilder("Ольга"),
            new StringBuilder("Блуд"),
            new StringBuilder("Иаков Черноризец"),
            new StringBuilder("Рогнеда"),
            new StringBuilder("Лишил полномочий"),
            new StringBuilder("Малуша"),
            new StringBuilder("Хамиде"),
            new StringBuilder("языческий храм"),
            new StringBuilder("храм"),
            new StringBuilder("кладбище"),
            new StringBuilder("Новгород"),
            new StringBuilder("Перун"),
            new StringBuilder("Симаргл"),
            new StringBuilder("Стрибог"),
            new StringBuilder("Симаргл"),
            new StringBuilder("Симаргл"),
            new StringBuilder("Дажьбог"),
            new StringBuilder("Стрибог"),
            new StringBuilder("350"),
            new StringBuilder("подрезание волос"),
            new StringBuilder("1"),
            new StringBuilder("придворный"),
            new StringBuilder("Хорс"),
            new StringBuilder("Куколь"),
            new StringBuilder("Схима"),
            new StringBuilder("Рясофор"),
            new StringBuilder("Перун"),
            new StringBuilder("Пономарь"),
            new StringBuilder("Постриг"),
            new StringBuilder("Пономарь"),
            new StringBuilder("Белец"),
            new StringBuilder("Клирос"),
            new StringBuilder("повозка"),
            new StringBuilder("978 г."),
            new StringBuilder("Византия"),
            new StringBuilder("Владимир"),
            new StringBuilder("984/985 г."),
            new StringBuilder("971 г."),
            new StringBuilder("Святослав"),
            new StringBuilder("989 г."),
            new StringBuilder("Хрисополь"),
            new StringBuilder("2500"),
            new StringBuilder("963/964 г."),
            new StringBuilder("Святыни"),
            new StringBuilder("Киев"),
            new StringBuilder("Константин VIII"),
            new StringBuilder("988 г. "),
            new StringBuilder("981 г."),
            new StringBuilder("977-979 гг."),
            new StringBuilder("Радимичей"),
            new StringBuilder("967 г."),
            new StringBuilder("983 г."),
            new StringBuilder("979 г."),
            new StringBuilder("977 г."),
            new StringBuilder("961 г."),
            new StringBuilder("985 г."),
            new StringBuilder("Михаил I"),
            new StringBuilder("980 г."),
            new StringBuilder("Булгары"),
            new StringBuilder("13"),
            new StringBuilder("Судислав"),
            new StringBuilder("Глеб")
    };

    public Question1() {}
}